### ISSUE TITLE
OffsetTimestampGenerator doesn't allow %message{XXXX} anymore | Interlok 5.0.0

### ISSUE THREAD

**Issue by hemakumarLNRS** [adaptris/interlok#1338]
In 5.0.0, com.adaptris.core.services.metadata.timestamp.OffsetTimestampGenerator.java doesn't seem to accept passing metadata values as part of the offset time. It might be because the regex check has been performed before the msg.resolve process itself and the regex doesn't include %message{XXXX} pattern. Hence regex matching failed on this pattern (PT%message{XXXX}S).

![image](https://github.com/adaptris/interlok/assets/88713387/011895f4-c7b9-4740-b5f5-9e41bd3638df)

PFB the error message thrown,
`com.adaptris.core.CoreException: Invalid offset pattern 'PT%message{ProductOffsetTime}S', you must use the ISO8601 standard. I.e. 'P30D', '-P30D'
        at com.adaptris.core.services.metadata.timestamp.OffsetTimestampGenerator.validateOffset(OffsetTimestampGenerator.java:155) ~[interlok-core.jar:5.0.0-RELEASE]`

**Comment by jameswickham** [comment]
issue fixed and will be included in the next release.

Jira ticket: INTERLOK-4249
