### ISSUE TITLE
Create a 4.2.1 release that contains  #783 as the hotfix

### ISSUE THREAD

**Issue by quotidian-ennui** [adaptris/interlok#786]
#783 forces the sort order to be alphabetical when figuring out jars to lad.

This  needs to be back-ported into a 4.2.1 release; you can cherry pick the changes out of the branch associated with #783 to do this.

Suggest you do something like (since there is not yet a support/4.2 branch

```
git flow support start 4.2 4.2.0
// This creates a branch support/4.2 based on the tag 4.2.0
git checkout -b "support/4.2"
// Create a branch now off the support branch.
git checkout -b "hotfix/4.2.1"
// Do WORK
// DO THE PUBLISH HERE...
git checkout support/4.2
git merge hotfix/4.2.1
git tag 4.2.1
// merge the hotfix into develop as well, cherry picking or whatever
// then we can delete the branch.
git branch -d "hotfix/4.2.1"
```

**Comment by higgyfella** [comment]
4.2.1 release done:
https://nexus.adaptris.net/nexus/content/repositories/releases/com/adaptris/interlok-core/4.2.1-RELEASE/
https://github.com/adaptris/interlok/tree/4.2.1

**Comment by quotidian-ennui** [comment]
This was the follow-on ticket from : https://github.com/adaptris/interlok/issues/782
